(() => {
  const $ = s => document.querySelector(s);
  const esc = v => String(v ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const isAdmin = () => JSON.parse(localStorage.getItem('nv_user') || '{}').role === 'admin';
  const style=document.createElement('style');style.textContent='.admin-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px;margin-bottom:14px}.metric{background:var(--soft);border-radius:15px;padding:14px}.metric strong{display:block;font-size:25px}.admin-tag{border-radius:99px;padding:5px 8px;background:#7c5cff22;color:#bbaeff;font-size:10px;font-weight:900}.admin-actions{display:flex;gap:7px;margin:10px 0 14px}nav.admin-nav{grid-template-columns:repeat(5,1fr)}';document.head.appendChild(style);
  async function renderAdmin(){const screen=$('#admin');if(!screen||!window.NearVibeAPI)return;try{const [o,d]=await Promise.all([window.NearVibeAPI.api('/admin/overview'),window.NearVibeAPI.api('/admin/reports')]),m=o.metrics;screen.innerHTML=`<div class="title"><div><p class="eyebrow">OWNER CONTROLS</p><h2>Admin</h2></div><span class="admin-tag">SECURE ADMIN</span></div><div class="admin-grid"><div class="metric"><strong>${m.users}</strong><span>Users</span></div><div class="metric"><strong>${m.openReports}</strong><span>Open reports</span></div><div class="metric"><strong>${m.pendingVerifications}</strong><span>Checks waiting</span></div><div class="metric"><strong>${m.activeCalls}</strong><span>Active calls</span></div></div><div class="card"><h3>Moderation queue</h3>${d.reports.length?d.reports.map(r=>`<div class="row"><span><strong>${esc(r.reported)}</strong><br><small>${esc(r.reason)} · reported by ${esc(r.reporter)}</small></span></div>${r.status==='open'?`<div class="admin-actions"><button class="danger suspend-account" data-id="${r.reported_user_id}">Suspend account</button></div>`:''}`).join(''):'<p>No reports.</p>'}</div>`;screen.querySelectorAll('.suspend-account').forEach(b=>b.onclick=async()=>{if(!confirm('Suspend this account and end all its sessions?'))return;try{await window.NearVibeAPI.api(`/admin/users/${b.dataset.id}/suspend`,{method:'POST'});toast('Account suspended');renderAdmin()}catch(e){toast(e.message)}})}catch(e){screen.innerHTML=`<div class="card"><h3>Admin unavailable</h3><p>${esc(e.message)}</p></div>`}}
  function enableAdmin(){if(!isAdmin()||$('#admin'))return;const screen=document.createElement('section');screen.id='admin';screen.className='screen';$('#profile').after(screen);const button=document.createElement('button');button.dataset.screen='admin';button.innerHTML='<span>⚙</span>Admin';$('nav').appendChild(button);$('nav').classList.add('admin-nav');button.onclick=()=>{document.querySelectorAll('nav button').forEach(x=>x.classList.remove('on'));button.classList.add('on');document.querySelectorAll('.screen').forEach(x=>x.classList.remove('on'));screen.classList.add('on');renderAdmin()};renderAdmin()}
  window.NearVibeEnableAdmin=enableAdmin;if(isAdmin())setTimeout(enableAdmin,250);
})();
