(() => {
  const api = async (path, options = {}) => {
    const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),20000);
    try { const response = await fetch(`/api${path}`, { credentials: 'same-origin', ...options, signal:controller.signal, headers: { 'content-type': 'application/json', ...(options.headers || {}) } });
      const data = await response.json().catch(() => ({ error: 'Unexpected server response.' }));
      if (!response.ok) throw new Error(data.error || 'Request failed.');
      return data;
    } catch(error) { if(error.name==='AbortError')throw new Error('Cloudflare took too long. Please try again.');throw error; } finally { clearTimeout(timer); }
  };
  const value = (form, selector) => form.querySelector(selector)?.value?.trim() || '';
  const esc = value => String(value ?? '').replace(/[&<>"']/g, character => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[character]));
  const launchProfiles=[{id:2,name:'Chloe AI',age:26,bio:'Virtual NearVibe guide who loves music, travel and good conversation.',approximate_area:'AI demo — no real location',photo_data:null,is_ai:1,is_demo:1,adult_status:'demo',call_price:30},{id:3,name:'Sophie AI',age:30,bio:'Virtual profile for safely testing matches, messages, calls and gifts.',approximate_area:'AI demo — no real location',photo_data:null,is_ai:1,is_demo:1,adult_status:'demo',call_price:40},{id:4,name:'Aisha AI',age:28,bio:'Friendly virtual account for exploring NearVibe features.',approximate_area:'AI demo — no real location',photo_data:null,is_ai:1,is_demo:1,adult_status:'demo',call_price:25}];
  let serverProfiles = [], profileIndex = 0, serverMatches = [], activeMatch = null, callInterval = null;

  function showUser(user) {
    document.querySelector('#auth').classList.add('hide'); document.querySelector('#main').classList.remove('hide');
    document.querySelector('#deck').innerHTML='<div class="card"><h3>Loading profiles…</h3><p>Checking the secure database.</p></div>';
    document.querySelector('#pname').textContent = user.name;
    const avatar = document.querySelector('#avatar'); avatar.textContent = user.name[0].toUpperCase();
    localStorage.setItem('nv_user', JSON.stringify({ id:user.id, name:user.name, email:user.email, role:user.role, server:true }));
    serverProfiles=launchProfiles;profileIndex=0;renderProfile();
    loadMatches();loadWallet();if(user.role === 'admin' && window.NearVibeEnableAdmin) window.NearVibeEnableAdmin();
  }
  async function loadMe() { try { const result=await api('/me'); showUser(result.user); if(result.user.photo_data){const a=document.querySelector('#avatar');a.style.backgroundImage=`url(${result.user.photo_data})`;a.textContent='';} } catch { if(localStorage.getItem('nv_user')) { localStorage.removeItem('nv_user'); location.reload(); } } }
  async function loadProfiles() { try { const r=await api('/profiles'); serverProfiles=r.profiles; profileIndex=0; renderProfile(); } catch(e){ document.querySelector('#deck').innerHTML=`<div class="card"><h3>Profiles took too long to load</h3><p>${esc(e.message)}</p><button id="retryProfiles" class="primary wide">Try again</button></div>`;document.querySelector('#retryProfiles').onclick=()=>{document.querySelector('#deck').innerHTML='<div class="card"><h3>Loading profiles…</h3><p>Checking the secure database.</p></div>';loadProfiles();};toast(e.message); } }
  function renderProfile() {
    const p=serverProfiles[profileIndex]; if(!p){document.querySelector('#deck').innerHTML='<div class="card"><h3>You’re all caught up</h3><p>More profiles will appear here.</p></div>';return;}
    document.querySelector('#deck').innerHTML=`<article class="profile"><div class="person" style="${p.photo_data?`background:url(${p.photo_data}) center/cover`:''}">${p.photo_data?'':esc(p.name[0])}</div><div class="info"><span class="badge">${p.is_ai?'✦ AI demo profile':p.adult_status==='verified'?'✓ Adult verified':'Photo profile'}</span><h3>${esc(p.name)}, ${Number(p.age)}</h3><p>📍 ${esc(p.approximate_area||'Approximate area only')}</p><p>${esc(p.bio||'New to NearVibe.')}</p><p>🪙 ${Number(p.call_price)} coins/min</p></div></article>`;
  }
  async function loadMatches(){try{const r=await api('/matches');serverMatches=r.matches;renderMatches();}catch{}}
  function renderMatches(){const html=serverMatches.map(m=>`<div class="item"><div class="avatar" style="${m.photo_data?`background:url(${m.photo_data}) center/cover`:''}">${m.photo_data?'':esc(m.name[0])}</div><div class="copy"><h3>${esc(m.name)}${m.is_ai?' · AI demo':''}</h3><p>${Number(m.call_price)} coins/min</p></div><button class="mini server-chat" data-id="${Number(m.id)}" data-name="${esc(m.name)}" data-user="${Number(m.user_id)}" data-ai="${Number(m.is_ai)}">Message</button></div>`).join('')||'<div class="card"><h3>No matches yet</h3><p>Mutual likes will appear here.</p></div>';document.querySelector('#matchlist').innerHTML=html;document.querySelector('#chatlist').innerHTML=html;}
  async function openChat(button){activeMatch={id:Number(button.dataset.id),name:button.dataset.name,userId:Number(button.dataset.user)};try{const r=await api(`/matches/${activeMatch.id}/messages`),me=JSON.parse(localStorage.nv_user||'{}');modal(`<p class="eyebrow">PRIVATE MESSAGE</p><h2>${esc(activeMatch.name)}</h2><p class="center">${button.dataset.ai==='1'?'This is a clearly labelled AI demo conversation.':'Messages are stored securely.'} Never share financial information.</p><div id="serverMessages">${r.messages.map(x=>`<div class="bubble ${x.sender_id===me.id?'me':''}">${esc(x.body)}${x.kind==='ai_demo'?'<br><small>AI demo reply</small>':''}</div>`).join('')}</div><div class="compose"><input id="serverMsg" maxlength="1000" placeholder="Write a respectful message"><button id="serverSend" class="primary">➤</button></div><div class="modalactions"><button id="serverGift" class="secondary">🎁 Gift</button><button id="serverCall" class="secondary">📹 Call offer</button><button id="serverReport" class="danger">Report / block</button></div>`);document.querySelector('#serverSend').onclick=async event=>{const input=document.querySelector('#serverMsg'),send=event.currentTarget;if(!input.value.trim())return;send.disabled=true;send.textContent='…';try{await api(`/matches/${activeMatch.id}/messages`,{method:'POST',body:JSON.stringify({body:input.value})});input.value='';await openChat(button);}catch(e){toast(e.message);send.disabled=false;send.textContent='➤';}};document.querySelector('#serverGift').onclick=giftPicker;document.querySelector('#serverCall').onclick=callOffer;document.querySelector('#serverReport').onclick=reportUser;}catch(e){toast(e.message);}}
  async function loadWallet(){try{const w=await api('/wallet');const b=document.querySelector('#coinBalance');if(b)b.textContent=w.balance;window.nvWallet=w;}catch{}}
  function openWallet(){const w=window.nvWallet;if(!w)return loadWallet().then(openWallet);modal(`<p class="eyebrow">SECURE WALLET</p><h2>NearVibe coins</h2><p>Balance: <strong>${w.balance} coins</strong></p><div class="packages">${w.packages.map(p=>`<button class="package server-package" data-id="${p.id}">${p.coins} 🪙<small>£${(p.price_pence/100).toFixed(2)}</small></button>`).join('')}</div><div class="ledger">${w.ledger.slice(0,8).map(x=>`${x.amount>0?'+':''}${x.amount} — ${x.type}`).join('<br>')||'No transactions yet.'}</div><p class="center">Payments use Stripe Checkout. Coins have no cash value.</p>`);document.querySelectorAll('.server-package').forEach(b=>b.onclick=async()=>{try{const r=await api('/payments/checkout',{method:'POST',body:JSON.stringify({packageId:b.dataset.id})});location.href=r.url;}catch(e){toast(e.message)}});}
  function giftPicker(){const w=window.nvWallet;if(!w)return;modal(`<p class="eyebrow">VIRTUAL GIFTS</p><h2>Send to ${esc(activeMatch.name)}</h2><p>Balance: ${Number(w.balance)} coins</p><div class="gifts">${w.gifts.map(g=>`<button class="gift server-gift" data-id="${esc(g.id)}">${esc(g.emoji)}<small>${Number(g.coin_cost)} coins</small></button>`).join('')}</div>`);document.querySelectorAll('.server-gift').forEach(b=>b.onclick=async()=>{try{await api(`/matches/${activeMatch.id}/gifts`,{method:'POST',body:JSON.stringify({giftId:b.dataset.id})});close();toast('Gift sent');loadWallet();}catch(e){toast(e.message)}});}
  async function startPaidCall(callId,rate){if(callInterval)clearInterval(callInterval);let minutes=0;const tick=async()=>{try{const r=await api(`/calls/${callId}/tick`,{method:'POST'});minutes=r.billedMinutes;document.querySelector('#paidMinutes').textContent=minutes;document.querySelector('#paidBalance').textContent=r.balance;loadWallet();}catch(e){clearInterval(callInterval);callInterval=null;toast(e.message);close();}};modal(`<p class="eyebrow">AI DEMO CALL</p><h2>${esc(activeMatch.name)}</h2><p>This is a billing demonstration; no live audio or video is connected.</p><div class="card center"><h1><span id="paidMinutes">0</span> min</h1><p>${rate} coins/min · Balance <span id="paidBalance">${window.nvWallet?.balance??'—'}</span></p></div><button id="endPaidCall" class="danger wide">End call</button>`);document.querySelector('#endPaidCall').onclick=async()=>{clearInterval(callInterval);callInterval=null;await api(`/calls/${callId}/end`,{method:'POST'});close();toast(`Call ended after ${minutes} minute${minutes===1?'':'s'}`);loadWallet();};await tick();if(document.querySelector('#paidMinutes'))callInterval=setInterval(tick,60000);}
  function callOffer(){modal(`<p class="eyebrow">CALL RATE</p><h2>Offer coins per minute</h2><label>Offer<input id="serverRate" type="number" min="5" max="500" step="5" value="30"></label><button id="sendOffer" class="primary wide">Send call offer</button><p class="center">AI demos accept test offers automatically. Every started minute is deducted by the server.</p>`);document.querySelector('#sendOffer').onclick=async()=>{try{const rate=Number(document.querySelector('#serverRate').value),r=await api(`/matches/${activeMatch.id}/call-offers`,{method:'POST',body:JSON.stringify({rate})});if(r.accepted)return startPaidCall(r.callId,r.rate);close();toast('Call offer sent');}catch(e){toast(e.message)}};}
  function reportUser(){modal(`<p class="eyebrow">SAFETY</p><h2>Report or block ${esc(activeMatch.name)}</h2><label>Reason<select id="serverReason"><option>Unwanted contact</option><option>Fake profile</option><option>Harassment or threats</option><option>Underage concern</option></select></label><div class="modalactions"><button id="serverBlock" class="danger">Block</button><button id="serverSubmitReport" class="secondary">Report</button></div>`);document.querySelector('#serverBlock').onclick=async()=>{await api(`/users/${activeMatch.userId}/block`,{method:'POST'});close();toast('Account blocked');loadMatches();};document.querySelector('#serverSubmitReport').onclick=async()=>{await api(`/users/${activeMatch.userId}/report`,{method:'POST',body:JSON.stringify({reason:document.querySelector('#serverReason').value})});close();toast('Report sent');};}

  document.querySelector('#signup').addEventListener('submit', async event => { event.preventDefault(); event.stopImmediatePropagation(); const f=event.currentTarget; try { const selects=f.querySelectorAll('select'); const r=await api('/auth/signup',{method:'POST',body:JSON.stringify({name:value(f,'[name=name]'),email:value(f,'input[type=email]'),password:value(f,'input[type=password]'),dob:value(f,'[name=dob]'),gender:selects[0].value,lookingFor:selects[1].value})});showUser(r.user);toast('Account created securely'); } catch(e){toast(e.message)} }, true);
  document.querySelector('#login').addEventListener('submit', async event => { event.preventDefault(); event.stopImmediatePropagation(); const f=event.currentTarget; try { const r=await api('/auth/login',{method:'POST',body:JSON.stringify({email:value(f,'input[type=email]'),password:value(f,'input[type=password]')})});showUser(r.user);toast('Logged in'); } catch(e){toast(e.message)} }, true);
  document.querySelector('#like').addEventListener('click',async e=>{if(!serverProfiles.length)return;e.stopImmediatePropagation();const p=serverProfiles[profileIndex];try{const r=await api(`/profiles/${p.id}/like`,{method:'POST'});if(r.matched)toast(`You matched with ${p.name}`);profileIndex++;renderProfile();loadMatches();}catch(err){toast(err.message)}},true);
  document.querySelector('#pass').addEventListener('click',e=>{if(!serverProfiles.length)return;e.stopImmediatePropagation();profileIndex++;renderProfile();},true);
  document.addEventListener('click',e=>{const b=e.target.closest('.server-chat');if(b){e.preventDefault();e.stopImmediatePropagation();openChat(b);}},true);
  document.querySelectorAll('nav button').forEach(button=>button.addEventListener('click',()=>{renderMatches();if(button.dataset.screen==='matches'||button.dataset.screen==='messages')loadMatches();}));
  document.querySelector('#wallet')?.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();openWallet();},true);
  document.querySelector('#photo').addEventListener('change',e=>{const file=e.target.files[0];if(!file||file.size>2e6)return toast('Choose an image under 2 MB');const reader=new FileReader();reader.onload=async()=>{try{await api('/me/photo',{method:'POST',body:JSON.stringify({photo:reader.result})});toast('Photo saved securely');loadMe();}catch(err){toast(err.message)}};reader.readAsDataURL(file);},true);
  document.querySelector('#logout').addEventListener('click',async e=>{e.preventDefault();e.stopImmediatePropagation();await api('/auth/logout',{method:'POST'});localStorage.clear();location.reload();},true);
  document.querySelector('#verify').addEventListener('click',async e=>{e.stopImmediatePropagation();try{await api('/verification/request',{method:'POST'});toast('Verification request opened');}catch(err){toast(err.message)}},true);
  loadMe();
  window.NearVibeAPI={api,loadWallet};
})();
