PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  email TEXT NOT NULL UNIQUE COLLATE NOCASE,
  password_hash TEXT NOT NULL,
  password_salt TEXT NOT NULL,
  name TEXT NOT NULL,
  dob TEXT NOT NULL,
  gender TEXT NOT NULL,
  looking_for TEXT NOT NULL,
  bio TEXT NOT NULL DEFAULT '',
  approximate_area TEXT NOT NULL DEFAULT '',
  photo_data TEXT,
  role TEXT NOT NULL DEFAULT 'user' CHECK(role IN ('user','admin','moderator')),
  status TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active','suspended','deleted')),
  is_ai INTEGER NOT NULL DEFAULT 0,
  is_demo INTEGER NOT NULL DEFAULT 0,
  adult_status TEXT NOT NULL DEFAULT 'unverified',
  paid_call_eligible INTEGER NOT NULL DEFAULT 0,
  call_price INTEGER NOT NULL DEFAULT 30 CHECK(call_price BETWEEN 5 AND 500),
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS sessions (id TEXT PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, token_hash TEXT NOT NULL UNIQUE, expires_at TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS idx_sessions_hash ON sessions(token_hash);
CREATE TABLE IF NOT EXISTS likes (from_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, to_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(from_user_id,to_user_id));
CREATE TABLE IF NOT EXISTS matches (id INTEGER PRIMARY KEY AUTOINCREMENT, user_a INTEGER NOT NULL REFERENCES users(id), user_b INTEGER NOT NULL REFERENCES users(id), created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(user_a,user_b));
CREATE TABLE IF NOT EXISTS messages (id INTEGER PRIMARY KEY AUTOINCREMENT, match_id INTEGER NOT NULL REFERENCES matches(id) ON DELETE CASCADE, sender_id INTEGER NOT NULL REFERENCES users(id), body TEXT NOT NULL, kind TEXT NOT NULL DEFAULT 'text', gift_id INTEGER, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS idx_messages_match ON messages(match_id,id);
CREATE TABLE IF NOT EXISTS wallets (user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE, balance INTEGER NOT NULL DEFAULT 0 CHECK(balance >= 0), updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS coin_transactions (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL REFERENCES users(id), amount INTEGER NOT NULL, type TEXT NOT NULL, reference_type TEXT, reference_id TEXT, idempotency_key TEXT UNIQUE, balance_after INTEGER NOT NULL, metadata TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS idx_ledger_user ON coin_transactions(user_id,id);
CREATE TABLE IF NOT EXISTS coin_packages (id TEXT PRIMARY KEY, name TEXT NOT NULL, coins INTEGER NOT NULL, price_pence INTEGER NOT NULL, stripe_price_id TEXT, active INTEGER NOT NULL DEFAULT 1);
INSERT OR IGNORE INTO coin_packages VALUES ('starter','Starter',50,199,NULL,1),('popular','Popular',150,499,NULL,1),('value','Best value',400,999,NULL,1);
CREATE TABLE IF NOT EXISTS gifts (id TEXT PRIMARY KEY, name TEXT NOT NULL, emoji TEXT NOT NULL, coin_cost INTEGER NOT NULL, active INTEGER NOT NULL DEFAULT 1);
INSERT OR IGNORE INTO gifts VALUES ('rose','Rose','🌹',5,1),('coffee','Coffee','☕',10,1),('diamond','Diamond','💎',25,1);
CREATE TABLE IF NOT EXISTS call_offers (id INTEGER PRIMARY KEY AUTOINCREMENT, match_id INTEGER NOT NULL REFERENCES matches(id), proposer_id INTEGER NOT NULL REFERENCES users(id), recipient_id INTEGER NOT NULL REFERENCES users(id), coins_per_minute INTEGER NOT NULL, status TEXT NOT NULL DEFAULT 'pending', parent_offer_id INTEGER, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, responded_at TEXT);
CREATE TABLE IF NOT EXISTS calls (id INTEGER PRIMARY KEY AUTOINCREMENT, match_id INTEGER NOT NULL REFERENCES matches(id), payer_id INTEGER NOT NULL REFERENCES users(id), recipient_id INTEGER NOT NULL REFERENCES users(id), rate INTEGER NOT NULL, status TEXT NOT NULL DEFAULT 'active', started_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, last_billed_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, billed_minutes INTEGER NOT NULL DEFAULT 0, ended_at TEXT);
CREATE TABLE IF NOT EXISTS reports (id INTEGER PRIMARY KEY AUTOINCREMENT, reporter_id INTEGER NOT NULL REFERENCES users(id), reported_user_id INTEGER NOT NULL REFERENCES users(id), reason TEXT NOT NULL, details TEXT NOT NULL DEFAULT '', status TEXT NOT NULL DEFAULT 'open', reviewed_by INTEGER, resolution TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, reviewed_at TEXT);
CREATE TABLE IF NOT EXISTS blocks (blocker_id INTEGER NOT NULL REFERENCES users(id), blocked_id INTEGER NOT NULL REFERENCES users(id), created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(blocker_id,blocked_id));
CREATE TABLE IF NOT EXISTS verification_requests (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL REFERENCES users(id), provider_reference TEXT, status TEXT NOT NULL DEFAULT 'pending', reviewed_by INTEGER, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, reviewed_at TEXT);
CREATE TABLE IF NOT EXISTS audit_log (id INTEGER PRIMARY KEY AUTOINCREMENT, actor_id INTEGER, action TEXT NOT NULL, target_type TEXT, target_id TEXT, metadata TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);

